### ISSUE TITLE
Charts are not pacakged

### ISSUE THREAD

**Issue by max-rocket-internet** [JimCronqvist/action-helm-chart-repo#1]
Heya,
I like this action as it handles a whole directory of charts as opposed to a single chart (like other actions) but for me it doesn't quite work.

My config looks like this:

```yaml
name: Helm Publish

on:
  push:
    branches:
    - main
    paths:
      - 'charts/**'
  workflow_dispatch:

jobs:
  helm:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.3
      - name: Build and Push charts to GitHub Container Registry
        uses: JimCronqvist/action-helm-chart-repo@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          chartsPath: charts
```

But the charts are not actually packaged:

```
Run JimCronqvist/action-helm-chart-repo@master
  with:
    token: ***
    chartsPath: charts
Run find ${CHARTS_PATH} -type f -name 'Chart.yaml' | sed -r 's|/[^/]+$||' | sort | uniq | xargs --verbose -L 1 helm dep up
  find ${CHARTS_PATH} -type f -name 'Chart.yaml' | sed -r 's|/[^/]+$||' | sort | uniq | xargs --verbose -L 1 helm dep up
  for d in ${CHARTS_PATH}*/ ; do
      if [[ ! -f "${d}Chart.yaml" ]]; then
          echo "${d}Chart.yaml not found. Skipping."
          continue
      fi
      echo "$d"
      helm package "$d" -u -d dist
  done
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    CHARTS_PATH: charts
helm dep up charts/aws-ebs-csi-driver
helm dep up charts/aws-service-quotas-exporter
helm dep up charts/aws-storage-class
helm dep up charts/k8s-event-logger
helm dep up charts/k8s-resources
charts/Chart.yaml not found. Skipping.
```

This causes the last step to fail with `No such file or directory` for `dist`.
